#!/bin/sh
set -euxo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $WALLABAG_DB_USER WITH PASSWORD '$WALLABAG_DB_PASS';
  CREATE DATABASE wallabag OWNER $WALLABAG_DB_USER;
EOSQL
